<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\ResultIterator;

use App\Domain\ResultIterator\Generated\AbstractCommentResultIterator;

/**
 * The CommentResultIterator class will iterate over results of Comment class.
 */
class CommentResultIterator extends AbstractCommentResultIterator
{
}
