<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\BaseComment;
use Symfony\Component\Validator\Constraints as Assert;
use TheCodingMachine\GraphQLite\Annotations as GraphQLite;

/**
 * The Comment class maps the 'comments' table in database.
 */


#[GraphQLite\Type]
#[GraphQLite\SourceField(name: 'id', outputType: 'ID')]
#[GraphQLite\SourceField(name: 'text')]

class Comment extends BaseComment
{
    public function __construct(
        string $text,
    ) {
        parent::__construct(
            text: $text
        );
    }

    /**
     * @Assert\NotBlank(message="not_blank")
     * @Assert\Length(max=255, maxMessage="max_length_255")
     */
    public function getText(): string
    {
        return parent::getText();
    }
}
